version: '3.4'

services:
  ruisantos.zocdoc.db:
    image: mongo:latest
    restart: always

  ruisantos.zocdoc.api:
    image: ${DOCKER_REGISTRY-}ruisantoszocdocapi
    depends_on:
      - ruisantos.zocdoc.db
    environment:
      - ConnectionStrings__Default=mongodb://ruisantos.zocdoc.db:27017/zocdoc
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: RuiSantos.ZocDoc.Api/Dockerfile